import type { Metadata } from "next";
import Link from "next/link";
import { Activity, ArrowRight, Check, Route, ShieldCheck, Users, Wrench } from "lucide-react";
import { Nav } from "@/components/Nav";
import { Footer } from "@/components/Footer";
import { PageFrame } from "@/components/PageFrame";
import { Reveal } from "@/components/Reveal";
import { EarlyAccessButton } from "@/components/EarlyAccessButton";
import { Button } from "@/components/Button";
import { DotGrid } from "@/components/DotGrid";
import { pageMeta } from "@/lib/seo";

export const metadata: Metadata = pageMeta({
  title: "MCP Observability for Servers and Agent Workflows | TrackMCP",
  description: "MCP observability for clients, tool discovery, sessions, errors, latency, retries, and workflow outcomes. See where your MCP server needs work.",
  path: "/mcp-observability",
});

const jsonLd = { "@context": "https://schema.org", "@type": "WebPage", "@id": "https://trackmcp.com/mcp-observability#webpage", url: "https://trackmcp.com/mcp-observability", name: "MCP Observability for Servers and Agent Workflows | TrackMCP", description: "MCP observability for clients, tools, sessions, errors, latency, retries, and workflow outcomes.", about: { "@id": "https://trackmcp.com/#organization" } };

const layers = [
  { icon: Users, name: "Connection", body: "Which client connected, with which transport and protocol version?", color: "bg-sky-100 text-sky-600" },
  { icon: Wrench, name: "Discovery", body: "What tools did the client see, and what did it choose to call?", color: "bg-violet-100 text-violet-600" },
  { icon: Activity, name: "Execution", body: "How long did each call take, and what result came back?", color: "bg-brand-soft text-brand-strong" },
  { icon: Route, name: "Session", body: "Where did the ordered workflow slow down or stop?", color: "bg-amber-100 text-amber-600" },
];

function SignalFlow() {
  return <div className="relative overflow-hidden rounded-2xl border border-line bg-white p-5 shadow-[0_30px_80px_-50px_rgba(10,10,10,0.35)] sm:p-7"><DotGrid className="scale-125 opacity-50" /><div className="relative"><div className="mb-6 flex items-center justify-between"><span className="text-[12px] font-medium uppercase tracking-[0.08em] text-faint">mcp request lifecycle</span><span className="inline-flex items-center gap-1.5 rounded-full bg-mint px-2.5 py-1 text-[11px] font-medium text-mint-ink"><span className="h-1.5 w-1.5 rounded-full bg-brand" /> observed</span></div><div className="grid gap-2.5 sm:grid-cols-4">{layers.map(({ icon: Icon, name, body, color }, i) => <div key={name} className="relative rounded-xl border border-line bg-paper p-4 sm:min-h-[154px]">{i < layers.length - 1 && <span aria-hidden className="absolute -right-3 top-1/2 z-10 hidden h-px w-3 bg-line-strong sm:block" />}<div className={`grid h-9 w-9 place-items-center rounded-lg ${color}`}><Icon size={17} /></div><p className="mt-4 text-[13.5px] font-semibold text-ink">{name}</p><p className="mt-1.5 text-[12.5px] leading-[1.5] text-muted">{body}</p></div>)}</div><div className="mt-4 rounded-xl border border-brand/25 bg-brand-soft/45 px-4 py-3 text-[13px] text-body"><span className="font-semibold text-brand-strong">Outcome:</span> the workflow completed after 4 tool calls</div></div></div>;
}

export default function McpObservabilityPage() {
  return <><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd).replace(/</g, "\\u003c") }} /><Nav /><main className="flex-1"><PageFrame>
    <section className="relative overflow-hidden border-b border-line"><div aria-hidden className="pointer-events-none absolute inset-x-0 top-0 h-[480px] bg-[radial-gradient(54%_40%_at_50%_-8%,rgba(22,163,74,0.08),transparent_72%)]" /><div aria-hidden className="bg-squares dots-mask-top pointer-events-none absolute inset-x-0 top-0 h-[420px] opacity-70" /><div className="relative mx-auto max-w-3xl px-6 pb-10 pt-14 text-center sm:pb-14 sm:pt-20"><Reveal><span className="inline-flex items-center gap-2 rounded-full border border-line bg-white px-3 py-1 text-[12px] font-medium text-brand shadow-sm"><span className="h-1.5 w-1.5 rounded-full bg-brand" /> MCP observability</span></Reveal><Reveal delay={0.06}><h1 className="mx-auto mt-5 max-w-[16ch] text-balance text-[38px] font-medium leading-[1.05] tracking-[-0.04em] text-ink sm:text-[56px]">Know where the job stops</h1></Reveal><Reveal delay={0.12}><p className="mx-auto mt-5 max-w-[58ch] text-[16px] leading-[1.55] text-muted sm:text-[18px]">Observe the path from client connection to completed workflow. TrackMCP gives MCP teams the context between a healthy transport and a useful result.</p></Reveal><Reveal delay={0.18}><div className="mt-8 flex flex-col items-center justify-center gap-3 sm:flex-row"><EarlyAccessButton size="lg" label="Observe your server" /><Button href="/mcp-server-analytics/quickstart" variant="ghost" size="lg">Start with the quickstart <ArrowRight size={16} /></Button></div></Reveal></div></section>

    <section className="relative overflow-hidden border-b border-line bg-mist"><div className="mx-auto max-w-6xl px-6 py-12 sm:py-20"><Reveal><SignalFlow /></Reveal></div></section>

    <section className="mx-auto max-w-6xl px-6 py-20 sm:py-24"><Reveal className="max-w-2xl"><span className="text-[12px] font-medium uppercase tracking-[0.04em] text-brand">Why MCP needs its own layer</span><h2 className="mt-3 text-[30px] font-medium leading-[1.1] tracking-[-0.02em] text-ink sm:text-[36px]">A green transport can still hide a broken workflow.</h2><p className="mt-4 max-w-[58ch] text-[16px] leading-[1.5] text-muted">MCP tool results can carry an application error inside a successful HTTP response. If monitoring only counts status codes, the agent’s failure disappears.</p></Reveal><div className="mt-12 grid gap-4 md:grid-cols-2"><Reveal y={22}><div className="rounded-2xl border border-line bg-paper p-6 sm:p-8"><div className="flex items-center justify-between border-b border-line pb-4"><span className="font-mono text-[12px] text-faint">transport</span><span className="rounded-full bg-mint px-2.5 py-1 font-mono text-[11px] text-mint-ink">200 OK</span></div><p className="mt-7 text-[25px] font-medium tracking-[-0.03em] text-ink">Looks healthy</p><p className="mt-2 text-[14px] leading-[1.6] text-muted">The network request completed and your endpoint responded.</p></div></Reveal><Reveal delay={0.08} y={22}><div className="rounded-2xl border border-amber-200 bg-amber-50 p-6 sm:p-8"><div className="flex items-center justify-between border-b border-amber-200 pb-4"><span className="font-mono text-[12px] text-amber-800">tool result</span><span className="rounded-full bg-amber-100 px-2.5 py-1 font-mono text-[11px] text-amber-700">isError: true</span></div><p className="mt-7 text-[25px] font-medium tracking-[-0.03em] text-amber-950">Agent is stuck</p><p className="mt-2 text-[14px] leading-[1.6] text-amber-900">The application failed, the agent retried, and the workflow never completed.</p></div></Reveal></div></section>

    <section className="border-y border-line bg-paper"><div className="mx-auto max-w-6xl px-6 py-20 sm:py-24"><Reveal className="mx-auto max-w-2xl text-center"><span className="text-[12px] font-medium uppercase tracking-[0.04em] text-brand">What to instrument</span><h2 className="mt-3 text-[30px] font-medium leading-[1.1] tracking-[-0.02em] text-ink sm:text-[36px]">Capture the signal at the boundary.</h2><p className="mx-auto mt-4 max-w-[54ch] text-[16px] leading-[1.5] text-muted">Keep the server and tools unchanged. Add context where the MCP request enters and leaves your process.</p></Reveal><div className="mt-12 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Connection", "client, transport, protocol, auth"], ["Catalog", "tools discovered and schemas"], ["Call", "tool, duration, result, retry"], ["Outcome", "completed, failed, or stopped"]].map(([title, body], i) => <Reveal key={title} delay={i * 0.06} y={20}><div className="lift h-full rounded-2xl border border-line bg-white p-5"><span className="font-mono text-[11px] text-brand">0{i + 1}</span><h3 className="mt-5 text-[16px] font-semibold text-ink">{title}</h3><p className="mt-2 text-[13.5px] leading-[1.6] text-muted">{body}</p></div></Reveal>)}</div></div></section>

    <section className="relative overflow-hidden bg-[#f0fdf4]"><div className="mx-auto max-w-6xl px-6 py-20 sm:py-24"><div className="grid items-center gap-12 lg:grid-cols-[0.8fr_1.2fr]"><Reveal><span className="inline-flex items-center gap-2 text-[12px] font-medium uppercase tracking-[0.04em] text-brand-strong"><ShieldCheck size={14} /> Safe by design</span><h2 className="mt-3 max-w-[16ch] text-[30px] font-medium leading-[1.1] tracking-[-0.02em] text-ink sm:text-[38px]">Observe without putting serving at risk.</h2><p className="mt-4 max-w-[44ch] text-[16px] leading-[1.55] text-muted">Redact sensitive fields in your process, send minimized metadata, and let telemetry fail open when the network is unavailable.</p><Link href="/security" className="mt-7 inline-flex items-center gap-1.5 text-[14px] font-medium text-brand-strong hover:underline">Read the security approach <ArrowRight size={15} /></Link></Reveal><Reveal delay={0.1} y={24}><div className="rounded-2xl border border-brand/20 bg-white p-6 shadow-[0_30px_80px_-50px_rgba(10,10,10,0.35)] sm:p-8"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-lg bg-brand text-white"><Check size={17} /></span><div><p className="text-[14px] font-semibold text-ink">MCP request observed</p><p className="text-[12px] text-muted">Telemetry flushed asynchronously</p></div></div><div className="mt-6 space-y-3 border-t border-line pt-5 text-[13px]"><div className="flex justify-between"><span className="text-muted">tool</span><span className="font-mono text-body">search_docs</span></div><div className="flex justify-between"><span className="text-muted">client</span><span className="font-mono text-body">Claude</span></div><div className="flex justify-between"><span className="text-muted">result</span><span className="font-mono text-brand-strong">completed</span></div></div></div></Reveal></div></div></section>

    <section className="mx-auto max-w-6xl px-6 py-20 sm:py-24"><Reveal y={24}><div className="relative overflow-hidden rounded-2xl bg-ink px-8 py-16 text-center text-white sm:px-12"><div aria-hidden className="pointer-events-none absolute inset-0 bg-grid opacity-[0.10]" /><div className="relative"><p className="text-[12px] font-medium uppercase tracking-[0.1em] text-emerald-300">MCP observability</p><h2 className="mt-4 text-[30px] font-medium leading-[1.1] tracking-[-0.02em] text-white sm:text-[36px]">See the first broken event.</h2><p className="mx-auto mt-4 max-w-[48ch] text-[16px] leading-[1.5] text-white/65">Instrument one server and follow one real workflow from connection to outcome.</p><div className="mt-8 flex flex-col items-center justify-center gap-3 sm:flex-row"><EarlyAccessButton variant="white" size="lg" label="Get started" /><Button href="/mcp-server-analytics" size="lg" className="border border-white/20 bg-transparent text-white hover:bg-white/10">See analytics</Button></div></div></div></Reveal></section>
  </PageFrame></main><Footer /></>;
}
