import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Check, CircleAlert, Terminal } from "lucide-react";
import { Nav } from "@/components/Nav";
import { Footer } from "@/components/Footer";
import { PageFrame } from "@/components/PageFrame";
import { Reveal } from "@/components/Reveal";
import { EarlyAccessButton } from "@/components/EarlyAccessButton";
import { Button } from "@/components/Button";
import { CodeWindow, Cm, Fn, K, Pn, Str } from "@/components/CodeWindow";
import { pageMeta } from "@/lib/seo";

export const metadata: Metadata = pageMeta({
  title: "MCP Server Analytics Quickstart | TrackMCP",
  description: "Instrument an existing TypeScript or Python MCP server with TrackMCP, send your first event, and verify tool analytics in the dashboard.",
  path: "/mcp-server-analytics/quickstart",
});

const checks = [
  ["No event", "Confirm the process has the right key and make a real tool call after restarting the server."],
  ["Wrong workspace", "Check that the key belongs to the workspace you are viewing."],
  ["Sensitive data", "Redact arguments and results locally. Send only the metadata your team needs."],
];

export default function McpAnalyticsQuickstartPage() {
  return <><Nav /><main className="flex-1"><PageFrame>
    <section className="relative overflow-hidden border-b border-line"><div aria-hidden className="pointer-events-none absolute inset-x-0 top-0 h-[430px] bg-[radial-gradient(54%_40%_at_50%_-8%,rgba(22,163,74,0.08),transparent_72%)]" /><div aria-hidden className="bg-squares dots-mask-top pointer-events-none absolute inset-x-0 top-0 h-[380px] opacity-70" /><div className="relative mx-auto max-w-3xl px-6 pb-10 pt-14 text-center sm:pb-14 sm:pt-20"><Reveal><span className="inline-flex items-center gap-2 rounded-full border border-line bg-white px-3 py-1 text-[12px] font-medium text-brand shadow-sm"><span className="h-1.5 w-1.5 rounded-full bg-brand" /> MCP analytics quickstart</span></Reveal><Reveal delay={0.06}><h1 className="mx-auto mt-5 max-w-[16ch] text-balance text-[38px] font-medium leading-[1.05] tracking-[-0.04em] text-ink sm:text-[56px]">Send your first MCP analytics event</h1></Reveal><Reveal delay={0.12}><p className="mx-auto mt-5 max-w-[58ch] text-[16px] leading-[1.55] text-muted sm:text-[18px]">Go from an existing server to a verified event in four small steps. Keep your tools unchanged and see the result in the dashboard.</p></Reveal><Reveal delay={0.18}><div className="mt-8 flex flex-col items-center justify-center gap-3 sm:flex-row"><EarlyAccessButton size="lg" label="Create a workspace" /><Button href="/docs" variant="ghost" size="lg">Open full docs <ArrowRight size={16} /></Button></div></Reveal></div></section>

    <section className="border-b border-line bg-mist"><div className="mx-auto max-w-5xl px-6 py-10 sm:py-14"><div className="grid gap-3 sm:grid-cols-4">{["Create a key", "Install the SDK", "Wrap the server", "Verify one call"].map((step, i) => <Reveal key={step} delay={i * 0.05} y={14}><div className="rounded-xl border border-line bg-white px-4 py-4"><span className="font-mono text-[11px] text-brand">0{i + 1}</span><p className="mt-3 text-[13.5px] font-semibold text-ink">{step}</p></div></Reveal>)}</div></div></section>

    <section className="mx-auto max-w-6xl px-6 py-20 sm:py-24"><div className="grid items-start gap-12 lg:grid-cols-[0.72fr_1.28fr] lg:gap-20"><Reveal className="lg:sticky lg:top-28"><span className="text-[12px] font-medium uppercase tracking-[0.04em] text-brand">01 · Create a key</span><h2 className="mt-3 max-w-[14ch] text-[30px] font-medium leading-[1.1] tracking-[-0.02em] text-ink sm:text-[38px]">Start with a workspace.</h2><p className="mt-4 max-w-[42ch] text-[16px] leading-[1.55] text-muted">Sign in to TrackMCP, create a workspace key, and keep it in the environment of the process that runs your server.</p><p className="mt-5 text-[13px] text-faint">Never commit the key or put it in a tool argument.</p></Reveal><Reveal delay={0.08} y={22}><CodeWindow file=".env" copyText="TRACKMCP_KEY=tmcp_..."><div><Pn>TRACKMCP_KEY</Pn>=<Str>tmcp_...</Str></div></CodeWindow></Reveal></div></section>

    <section className="border-y border-line bg-paper"><div className="mx-auto max-w-6xl px-6 py-20 sm:py-24"><div className="grid items-start gap-12 lg:grid-cols-[0.72fr_1.28fr] lg:gap-20"><Reveal><span className="text-[12px] font-medium uppercase tracking-[0.04em] text-brand">02–03 · Install and wrap</span><h2 className="mt-3 max-w-[14ch] text-[30px] font-medium leading-[1.1] tracking-[-0.02em] text-ink sm:text-[38px]">One line at the boundary.</h2><p className="mt-4 max-w-[42ch] text-[16px] leading-[1.55] text-muted">Install the SDK and wrap the existing server object. Your tool definitions and client-facing responses stay the same.</p><div className="mt-6 flex flex-wrap gap-2 text-[12px] font-medium"><span className="rounded-full border border-line bg-white px-3 py-1.5 text-body">TypeScript</span><Link href="/docs/python" className="rounded-full border border-line bg-white px-3 py-1.5 text-brand-strong hover:border-line-strong">Python SDK <ArrowRight size={13} className="ml-1 inline" /></Link></div></Reveal><Reveal delay={0.08} y={22}><CodeWindow file="server.ts" copyText={'npm install @trackmcp/sdk\n\nimport { withTrackMCP } from "@trackmcp/sdk";\nimport { server } from "./mcp";\n\nexport default withTrackMCP(server, {\n  apiKey: process.env.TRACKMCP_KEY,\n  service: "acme-mcp-server",\n});'}><div><Cm>{"// observe the server you already ship"}</Cm></div><div><Pn>$</Pn> npm install <Str>@trackmcp/sdk</Str></div><div>&nbsp;</div><div><K>import</K> &#123; <Fn>withTrackMCP</Fn> &#125; <K>from</K> <Str>&quot;@trackmcp/sdk&quot;</Str></div><div><K>import</K> &#123; server &#125; <K>from</K> <Str>&quot;./mcp&quot;</Str></div><div>&nbsp;</div><div><K>export default</K> <Fn>withTrackMCP</Fn>(server, &#123;</div><div>  apiKey: process.env.<Pn>TRACKMCP_KEY</Pn>,</div><div>  service: <Str>&quot;acme-mcp-server&quot;</Str>,</div><div>&#125;);</div></CodeWindow></Reveal></div></div></section>

    <section className="mx-auto max-w-6xl px-6 py-20 sm:py-24"><div className="grid items-start gap-12 lg:grid-cols-[0.72fr_1.28fr] lg:gap-20"><Reveal><span className="text-[12px] font-medium uppercase tracking-[0.04em] text-brand">04 · Verify</span><h2 className="mt-3 max-w-[14ch] text-[30px] font-medium leading-[1.1] tracking-[-0.02em] text-ink sm:text-[38px]">Make one real tool call.</h2><p className="mt-4 max-w-[42ch] text-[16px] leading-[1.55] text-muted">Restart the server, connect from an MCP client, and call one tool. The dashboard should show the client, session, call, timing, and result state.</p><div className="mt-7 rounded-2xl border border-brand/20 bg-brand-soft/45 p-5"><p className="flex items-center gap-2 text-[14px] font-semibold text-ink"><Check size={17} className="text-brand" /> Success looks like a live event</p><p className="mt-2 text-[13.5px] leading-[1.6] text-body">Errors returned inside a successful HTTP response remain visible as application errors.</p></div></Reveal><Reveal delay={0.08} y={22}><div className="rounded-2xl border border-line bg-white p-6 shadow-[0_30px_80px_-50px_rgba(10,10,10,0.35)] sm:p-8"><div className="flex items-center gap-3 border-b border-line pb-5"><span className="grid h-9 w-9 place-items-center rounded-lg bg-brand text-white"><Terminal size={17} /></span><div><p className="text-[14px] font-semibold text-ink">First event received</p><p className="text-[12px] text-muted">acme-mcp-server · just now</p></div><span className="ml-auto h-2 w-2 rounded-full bg-brand" /></div><div className="mt-6 space-y-4 font-mono text-[12.5px]"><div className="flex justify-between"><span className="text-faint">client</span><span className="text-body">Claude</span></div><div className="flex justify-between"><span className="text-faint">method</span><span className="text-body">tools/call</span></div><div className="flex justify-between"><span className="text-faint">tool</span><span className="text-body">search_docs</span></div><div className="flex justify-between"><span className="text-faint">result</span><span className="text-brand-strong">completed</span></div></div></div></Reveal></div></section>

    <section className="border-y border-line bg-mist"><div className="mx-auto max-w-6xl px-6 py-20 sm:py-24"><Reveal className="mx-auto max-w-2xl text-center"><span className="inline-flex items-center gap-2 text-[12px] font-medium uppercase tracking-[0.04em] text-brand"><CircleAlert size={14} /> Before you debug</span><h2 className="mt-3 text-[30px] font-medium leading-[1.1] tracking-[-0.02em] text-ink sm:text-[36px]">Check the simple things first.</h2></Reveal><div className="mx-auto mt-12 max-w-3xl space-y-3">{checks.map(([title, body], i) => <Reveal key={title} delay={i * 0.06} y={16}><div className="grid gap-2 rounded-2xl border border-line bg-white px-5 py-4 sm:grid-cols-[0.45fr_1fr] sm:gap-8 sm:px-6"><p className="text-[14px] font-semibold text-ink">{title}</p><p className="text-[13.5px] leading-[1.55] text-muted">{body}</p></div></Reveal>)}</div></div></section>

    <section className="mx-auto max-w-6xl px-6 py-20 sm:py-24"><Reveal y={24}><div className="relative overflow-hidden rounded-2xl bg-ink px-8 py-16 text-center text-white sm:px-12"><div aria-hidden className="pointer-events-none absolute inset-0 bg-grid opacity-[0.10]" /><div className="relative"><p className="inline-flex items-center gap-2 text-[12px] font-medium uppercase tracking-[0.1em] text-emerald-300">Ready to observe your server?</p><h2 className="mt-4 text-[30px] font-medium leading-[1.1] tracking-[-0.02em] text-white sm:text-[36px]">Start with one real workflow.</h2><p className="mx-auto mt-4 max-w-[48ch] text-[16px] leading-[1.5] text-white/65">Create a workspace, wrap the server, and make the first call.</p><div className="mt-8 flex flex-col items-center justify-center gap-3 sm:flex-row"><EarlyAccessButton variant="white" size="lg" label="Get started" /><Button href="/mcp-server-analytics" size="lg" className="border border-white/20 bg-transparent text-white hover:bg-white/10">See analytics</Button></div></div></div></Reveal></section>
  </PageFrame></main><Footer /></>;
}
