'use client'

import { useState, useEffect, useMemo } from 'react'
import dynamic from 'next/dynamic'
import { SearchBar } from '@/components/SearchBar'
import { FilterBar } from '@/components/FilterBar'
import { CategoryFilter } from '@/components/CategoryFilter'
import { ToolCard } from '@/components/ToolCard'
import { StatsSection } from '@/components/StatsSection'
import { ErrorBoundary } from '@/components/error-boundary'
import { RotatingText } from '@/components/RotatingText'
import { Loader2, Sparkles, Package, X, Filter } from 'lucide-react'
import type { Database } from '@/types/database.types'

// Lazy load heavy components
const SubmitToolDialog = dynamic(() => import('@/components/SubmitToolDialog').then(mod => ({ default: mod.SubmitToolDialog })), {
  ssr: false,
  loading: () => null
})
const Footer = dynamic(() => import('@/components/Footer').then(mod => ({ default: mod.Footer })), {
  loading: () => null
})

type McpTool = Database['public']['Tables']['mcp_tools']['Row']

interface HomeClientProps {
  initialTools: McpTool[]
  totalCount: number
}

export function HomeClient({ initialTools, totalCount }: HomeClientProps) {
  const [inputValue, setInputValue] = useState('')
  const [searchQuery, setSearchQuery] = useState('')
  const [sortBy, setSortBy] = useState('stars')
  const [selectedCategory, setSelectedCategory] = useState('all')
  const [visibleCount, setVisibleCount] = useState(12)
  const [allTools, setAllTools] = useState<McpTool[]>(initialTools)
  const [isLoadingMore, setIsLoadingMore] = useState(false)
  const [isFilterBarSticky, setIsFilterBarSticky] = useState(false)

  // Debounce search query
  useEffect(() => {
    const timer = setTimeout(() => {
      setSearchQuery(inputValue)
    }, 300)

    return () => clearTimeout(timer)
  }, [inputValue])

  // Handle sticky filter bar on scroll
  useEffect(() => {
    const handleScroll = () => {
      const scrollPosition = window.scrollY
      setIsFilterBarSticky(scrollPosition > 400)
    }

    window.addEventListener('scroll', handleScroll)
    return () => window.removeEventListener('scroll', handleScroll)
  }, [])

  // Remove all filters
  const clearAllFilters = () => {
    setSelectedCategory('all')
    setSearchQuery('')
    setInputValue('')
  }

  // Count active filters
  const activeFilterCount = useMemo(() => {
    let count = 0
    if (selectedCategory !== 'all') count++
    if (searchQuery) count++
    return count
  }, [selectedCategory, searchQuery])

  // List of blocked repos to hide from UI (repos that cause 404 or are invalid)
  // Generated by: npm run find-404s
  const blockedRepos = useMemo(() => ['awesome-mcp-servers', 'context7', 'github-mcp-server', 'blender-mcp', 'chrome-devtools-mcp', 'browser-tools-mcp', 'mcp-atlassian', 'exa-mcp-server', 'mcp-server-cloudflare', 'apple-mcp', 'mcp-server-browserbase', 'excel-mcp-server', 'ableton-mcp', 'mcp-proxy', 'arxiv-mcp-server', 'brightdata-mcp', 'dbhub', 'azure-mcp', 'mcp-server-chatsum', 'elevenlabs-mcp', 'agent-toolkit', 'azure-devops-mcp', 'imcp', 'mcp-browser-use', 'google-calendar-mcp', 'gitlab-mcp', 'context-portal', 'mcp-server-docker', 'mcp-clickhouse', 'duckduckgo-mcp-server', 'mcp-server-elasticsearch', 'apify-mcp-server', 'cloud-run-mcp', 'clickup-mcp-server', 'docker-mcp', 'applescript-mcp', 'evm-mcp-server', 'devtools-debugger-mcp', 'davinci-resolve-mcp', 'mcp-server-airbnb', 'mcp-apple-notes', 'db-mcp-server', 'mcp-servers-hub', 'aws-mcp', 'aider-mcp-server', 'deepseek-mcp-server', 'deep-research-mcp', 'code-sandbox-mcp', 'dify-mcp-server', 'mcp-documentation-server', 'mcp-database-server', 'codegraphcontext', 'k8s-mcp-server', 'bilibili-mcp-server', 'anki-mcp-server', 'cli-mcp-server', 'git-mcp-server', 'app-store-connect-mcp-server', 'mcp-bigquery-server', 'mcp-discord', 'comfyui-mcp-server', 'mcp-server-bigquery', 'dart-mcp-server', 'mcp-3d-printer-server', 'a2a-mcp-server', 'backlog-mcp-server', 'mcp-server-asana', 'chronulus-mcp', 'discord-mcp', 'agentcare-mcp', 'coincap-mcp', 'easy-mcp-autocad', 'mcp-server', 'browser-mcp', 'mcp-server-atlassian-bitbucket', 'mcp-server-gsc', 'mcp-deepwebresearch', 'alpha-vantage-mcp', 'mcp-excel-server', 'cursor-mcp-installer', 'airtable-mcp', 'onchain-mcp', 'dicom-mcp', 'mcp-server-circleci', 'bitcoin-mcp', 'mcp-server-email', 'binance-mcp', 'mcp-for-api', 'mcp-server-axiom', 'computer-control-mcp', 'datadog-mcp-server', 'mcp-server-ccxt', 'fhir-mcp-server', 'mcp-server-flomo', 'mcp-server-azure-ai-agents', 'chess-mcp', 'deepseek-claude-mcp-server', 'deepl-mcp-server', 'claude-search-mcp', 'mcp-server-drupal', 'gomcp', 'ai-agent-marketplace-index-mcp', 'deepsrt-mcp', 'chrome-debug-mcp', 'mcp-databricks-server', 'bear-mcp-server', 'databricks-mcp-server', 'algorand-mcp', 'better-auth-mcp-server', 'api-mcp-server', 'cursor-mcp', 'mcp-dnstwist', 'esa-mcp-server', 'dappier-mcp', 'azure-devops-mcp-server', 'anki-mcp', 'app-seo-ai', 'mcp-server-dumplingai', 'apollo-io-mcp-server', 'binancemcpserver', 'mcp-etherscan-server', 'bluesky-context-server', 'alphafold-mcp-server', 'excel-reader-mcp', 'crawl4ai-mcp', 'descope-mcp-server-stdio', 'dbx-mcp-server', 'hubspot-mcp', 'confluence-mcp', 'mcp-datetime', 'emqx-mcp-server', 'cmd-mcp-server', 'attio-mcp-server', 'biorxiv-mcp-server', 'mcp-accessibility-scanner', 'directus-mcp', 'code-context-provider-mcp', 'binance-mcp-server', 'mcp-audiense-insights', 'microcms-mcp-server', 'calendar-mcp', 'daytona-mcp-interpreter', 'dify-workflow-mcp', 'congress_gov_mcp', 'dokploy-mcp', 'amazon-ads-mcp-server', 'mcp-chess', 'bluesky-mcp', 'cosa-sai', 'beyond-mcp-server', 'blockchain-mcp'], [])

  const filteredAndSortedTools = useMemo(() => {
    return allTools
      .filter((tool) => {
        // Filter out tools with missing essential data (would cause 404)
        if (!tool.repo_name || !tool.github_url) {
          return false
        }

        // Filter out blocked repos
        if (blockedRepos.includes(tool.repo_name?.toLowerCase() || '')) {
          return false
        }

        // Category filter
        if (selectedCategory !== 'all') {
          if (selectedCategory === 'featured') {
            // Featured tools - will be empty for now until user provides list
            return false
          } else {
            if (tool.category !== selectedCategory) {
              return false
            }
          }
        }

        // Search filter
        const searchLower = searchQuery.toLowerCase()
        return (
          tool.repo_name?.toLowerCase().includes(searchLower) ||
          tool.description?.toLowerCase().includes(searchLower) ||
          tool.topics?.some((topic) => topic.toLowerCase().includes(searchLower))
        )
      })
      .sort((a, b) => {
        switch (sortBy) {
          case 'stars':
            return (b.stars || 0) - (a.stars || 0)
          case 'recent':
            // Handle null/undefined dates - put them at the end
            if (!a.last_updated && !b.last_updated) return 0
            if (!a.last_updated) return 1
            if (!b.last_updated) return -1
            // Sort by most recent first (descending)
            const dateA = new Date(a.last_updated).getTime()
            const dateB = new Date(b.last_updated).getTime()
            return dateB - dateA
          case 'name':
            return (a.repo_name || '').localeCompare(b.repo_name || '')
          default:
            return 0
        }
      })
  }, [allTools, searchQuery, sortBy, selectedCategory])

  const totalStars = useMemo(() => {
    return filteredAndSortedTools.reduce((sum, tool) => sum + (tool.stars || 0), 0)
  }, [filteredAndSortedTools])

  // Calculate actual available tools count (excluding blocked/invalid tools)
  const actualAvailableCount = useMemo(() => {
    return allTools.filter(tool => {
      // Apply same filtering logic as filteredAndSortedTools
      if (!tool.repo_name || !tool.github_url) return false
      if (blockedRepos.includes(tool.repo_name?.toLowerCase() || '')) return false
      return true
    }).length
  }, [allTools, blockedRepos])

  // Get top 5 tools with highest stars for trending badge
  const top5RecentTools = useMemo(() => {
    const sorted = [...allTools].sort((a, b) => (b.stars || 0) - (a.stars || 0))
    return new Set(sorted.slice(0, 5).map(tool => tool.id))
  }, [allTools])

  // Show visibleCount tools when no search query, show all when searching
  const displayedTools = searchQuery ? filteredAndSortedTools : filteredAndSortedTools.slice(0, visibleCount)
  
  const hasMoreToLoad = !searchQuery && visibleCount < filteredAndSortedTools.length
  const remainingCount = filteredAndSortedTools.length - visibleCount

  const loadMore = async () => {
    // If we have more tools in memory, just show them
    if (visibleCount < allTools.length) {
      setVisibleCount(prev => prev + 12)
      return
    }
    
    // Otherwise, fetch more from API
    if (allTools.length < totalCount && !isLoadingMore) {
      setIsLoadingMore(true)
      try {
        const response = await fetch(`/api/tools?offset=${allTools.length}&limit=100`)
        const data = await response.json()
        if (data.tools && data.tools.length > 0) {
          setAllTools(prev => [...prev, ...data.tools])
          setVisibleCount(prev => prev + 12)
        }
      } catch (error) {
        console.error('Error loading more tools:', error)
      } finally {
        setIsLoadingMore(false)
      }
    }
  }

  // Reset visible count when search query changes
  useEffect(() => {
    if (searchQuery) {
      setVisibleCount(15)
    }
  }, [searchQuery])

  return (
    <div className="min-h-screen bg-background">
      {/* Hero Section */}
      <section className="relative min-h-[45vh] flex items-center justify-center overflow-x-hidden" aria-label="Hero section">
        {/* Animated background gradient */}
        <div className="absolute inset-0 bg-gradient-to-br from-primary/5 via-background to-accent/5" />
        
        {/* Gradient fade to background */}
        <div 
          className="absolute bottom-0 inset-x-0 h-20 pointer-events-none"
          style={{ background: 'linear-gradient(to bottom, transparent, var(--background))' }}
        />
        
        {/* Animated gradient orbs */}
        <div className="absolute top-0 left-1/4 w-96 h-96 bg-primary/20 rounded-full blur-3xl animate-pulse" />
        <div className="absolute bottom-0 right-1/4 w-96 h-96 bg-accent/20 rounded-full blur-3xl animate-pulse delay-700" />
        
        {/* Slim Ribbon Stats Banner - Positioned at top of hero section - Hidden on mobile */}
        <div className="hidden md:block">
          <StatsSection totalTools={searchQuery || selectedCategory !== 'all' ? filteredAndSortedTools.length : actualAvailableCount} totalStars={totalStars} isSearching={!!searchQuery || selectedCategory !== 'all'} />
        </div>
        
        <div className="container relative mx-auto px-4 py-4 md:py-6">
          <div className="max-w-5xl mx-auto text-center space-y-6">
            <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full border bg-card/50 backdrop-blur-sm mb-6 animate-fade-in">
              <Sparkles className="h-4 w-4 text-primary" />
              <span className="text-sm font-medium">Track MCP</span>
            </div>
            
            <h1 className="text-5xl md:text-7xl font-bold animate-fade-in leading-tight">
              <span className="gradient-text">World&apos;s Largest MCP</span>
              <br />
              {/* Mobile: Static text */}
              <span className="md:hidden gradient-text">Repository</span>
              {/* Desktop: Rotating text */}
              <span className="hidden md:inline whitespace-nowrap">
                <span className="text-accent">
                  <RotatingText words={['Server', 'Clients', 'Tools']} interval={3000} />
                </span>
                {' '}
                <span className="gradient-text">Repository</span>
              </span>
            </h1>
            
            <p className="text-base md:text-xl lg:text-2xl text-muted-foreground max-w-3xl mx-auto leading-relaxed animate-fade-in">
              Discover, Track, and Explore Over 10,000+ Model Context Protocol Servers, Clients & Tools in One Centralized Platform
            </p>
            
            <div className="flex flex-col items-center gap-2 pt-4 animate-fade-in relative z-50">
              <SearchBar
                value={inputValue}
                onChange={setInputValue}
                placeholder="Search by name, description, or tags..."
                tools={allTools}
              />
            </div>
          </div>
        </div>
      </section>

      {/* Main Content */}
      <main>
        {/* Filter Section - Grouped with subtle background */}
        <section className="container mx-auto px-4 mt-4 relative z-10" aria-label="Filter and search tools">
        <div className="bg-card/20 backdrop-blur-sm rounded-lg p-4 border border-border/50">
          {/* Category Filter */}
          <div className="mb-0">
            <CategoryFilter 
              selectedCategory={selectedCategory} 
              onCategoryChange={setSelectedCategory} 
            />
          </div>
        </div>
        
        {/* Submit Tool button - visible on mobile only, centered below stats */}
        <div className="flex justify-center mt-3 sm:hidden">
          <SubmitToolDialog />
        </div>
      </section>

      {/* Sticky Filter Bar */}
      {isFilterBarSticky && (
        <div className="fixed top-0 left-0 right-0 z-40 bg-background/95 backdrop-blur-md border-b shadow-lg animate-in slide-in-from-top duration-300">
          <div className="container mx-auto px-4 py-3">
            <div className="flex items-center justify-between gap-4">
              <div className="flex items-center gap-3">
                <Filter className="h-5 w-5 text-primary" />
                <span className="text-base md:text-sm font-semibold">
                  {searchQuery || selectedCategory !== 'all' ? filteredAndSortedTools.length.toLocaleString() : (10000 + actualAvailableCount).toLocaleString()} Available
                </span>
                {activeFilterCount > 0 && (
                  <span className="text-sm md:text-xs text-muted-foreground">({activeFilterCount} filters)</span>
                )}
              </div>
              <div className="flex items-center gap-2">
                <FilterBar sortBy={sortBy} onSortChange={setSortBy} />
                {activeFilterCount > 0 && (
                  <button
                    onClick={clearAllFilters}
                    className="text-xs text-muted-foreground hover:text-primary transition-colors underline"
                  >
                    Clear all
                  </button>
                )}
              </div>
            </div>
          </div>
        </div>
      )}

        {/* Directory Section */}
        <section className="container mx-auto px-4 pt-4 pb-6" aria-label="MCP tools listing">
          <h2 className="sr-only">Available MCP Tools</h2>
        <div className="flex flex-col gap-2 mb-3">
          <div className="flex flex-col gap-2">
            <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-3">
              <div>
                <p className="gradient-text text-xl md:text-lg font-bold">
                  {searchQuery || selectedCategory !== 'all' ? filteredAndSortedTools.length.toLocaleString() : (10000 + actualAvailableCount).toLocaleString()} Available
                </p>
              </div>
              <div className="flex flex-row gap-2 w-auto">
                <FilterBar 
                  sortBy={sortBy} 
                  onSortChange={setSortBy}
                />
              </div>
            </div>
          </div>

          {/* Active Filter Chips */}
          {activeFilterCount > 0 && (
            <div className="flex flex-wrap items-center gap-2 p-3 bg-card/30 rounded-lg border">
              <span className="text-base md:text-sm font-medium text-muted-foreground">Active filters:</span>
              
              {/* Category chip */}
              {selectedCategory !== 'all' && (
                <button
                  onClick={() => setSelectedCategory('all')}
                  className="inline-flex items-center gap-1.5 px-3 py-2 text-base md:text-sm bg-primary/10 text-primary rounded-full hover:bg-primary/20 transition-colors group min-h-[36px] md:min-h-[32px]"
                >
                  <span>{selectedCategory}</span>
                  <X className="h-3 w-3 group-hover:scale-110 transition-transform" />
                </button>
              )}

              {/* Search query chip */}
              {searchQuery && (
                <button
                  onClick={() => { setSearchQuery(''); setInputValue(''); }}
                  className="inline-flex items-center gap-1.5 px-3 py-2 text-base md:text-sm bg-accent/50 text-accent-foreground rounded-full hover:bg-accent transition-colors group min-h-[36px] md:min-h-[32px]"
                >
                  <span>Search: &quot;{searchQuery}&quot;</span>
                  <X className="h-3 w-3 group-hover:scale-110 transition-transform" />
                </button>
              )}

              {/* Clear all button */}
              <button
                onClick={clearAllFilters}
                className="ml-auto text-sm text-muted-foreground hover:text-primary transition-colors underline"
              >
                Clear all
              </button>
            </div>
          )}
        </div>

        {filteredAndSortedTools.length === 0 ? (
          <div className="text-center py-32 space-y-4">
            <div className="w-24 h-24 mx-auto rounded-full bg-muted flex items-center justify-center mb-6">
              <Package className="h-12 w-12 text-muted-foreground" />
            </div>
            <h3 className="text-2xl font-semibold">
              {searchQuery ? 'No tools found' : 'No tools yet'}
            </h3>
            <p className="text-xl text-muted-foreground max-w-md mx-auto">
              {searchQuery
                ? 'Try adjusting your search or filters'
                : 'Be the first to submit an MCP tool to the directory!'}
            </p>
          </div>
        ) : (
          <>
            <ErrorBoundary>
              <div 
                id="rows-container" 
                className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 auto-rows-fr"
                aria-live="polite"
              >
                {displayedTools.map((tool, index) => (
                <div
                  key={tool.id}
                  className="animate-fade-in h-full"
                  style={{
                    animationDelay: index >= visibleCount - 15 ? `${(index % 15) * 30}ms` : '0ms'
                  }}
                >
                  <ToolCard
                    name={tool.repo_name || 'Unknown'}
                    description={tool.description || ''}
                    stars={tool.stars || 0}
                    githubUrl={tool.github_url}
                    language={tool.language || undefined}
                    topics={tool.topics || undefined}
                    lastUpdated={tool.last_updated || undefined}
                    isTrending={top5RecentTools.has(tool.id)}
                  />
                </div>
              ))}
              </div>
            </ErrorBoundary>
            
            {/* Explore More Button */}
            {hasMoreToLoad && (
              <div className="flex justify-center mt-8">
                <button
                  onClick={loadMore}
                  disabled={isLoadingMore}
                  className="group relative px-6 py-2.5 rounded-md font-bold text-sm transition-all duration-200 focus:outline-none focus:ring-2 focus:ring-primary/30 focus:ring-offset-1 bg-gradient-to-r from-primary/10 via-accent/10 to-primary/10 hover:from-primary/20 hover:via-accent/20 hover:to-primary/20 disabled:opacity-50 disabled:cursor-not-allowed"
                  style={{ color: 'transparent' }}
                >
                  {isLoadingMore ? (
                    <span className="flex items-center gap-2 gradient-text">
                      <Loader2 className="h-4 w-4 animate-spin" />
                      Loading...
                    </span>
                  ) : (
                    <span className="gradient-text">
                      Explore more
                    </span>
                  )}
                </button>
              </div>
            )}
            
            {!hasMoreToLoad && !searchQuery && filteredAndSortedTools.length > 15 && (
              <div className="flex justify-center mt-12">
                <div className="px-8 py-4 rounded-lg font-semibold text-base text-muted-foreground">
                  No more results
                </div>
              </div>
            )}
          </>
        )}
        </section>
      </main>

      <Footer />
    </div>
  )
}
