import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, CircleAlert, Globe, LockKeyhole, Route, ShieldCheck } from "lucide-react";
import { Nav } from "@/components/Nav";
import { Footer } from "@/components/Footer";
import { PageFrame } from "@/components/PageFrame";
import { Reveal } from "@/components/Reveal";
import { EarlyAccessButton } from "@/components/EarlyAccessButton";
import { Button } from "@/components/Button";
import { DotGrid } from "@/components/DotGrid";
import { pageMeta } from "@/lib/seo";

export const metadata: Metadata = pageMeta({
  title: "MCP Observability for Remote HTTP Servers | TrackMCP",
  description: "Observe remote MCP HTTP servers across transport, authorization, tool calls, latency, retries, and workflow outcomes.",
  path: "/mcp-observability/remote-http",
});

const jsonLd = { "@context": "https://schema.org", "@type": "WebPage", "@id": "https://trackmcp.com/mcp-observability/remote-http#webpage", url: "https://trackmcp.com/mcp-observability/remote-http", name: "MCP Observability for Remote HTTP Servers | TrackMCP", description: "Observe remote MCP HTTP servers across transport, authorization, tool calls, latency, retries, and workflow outcomes.", about: { "@id": "https://trackmcp.com/#organization" } };

const checks = [
  [Globe, "Transport", "Did the remote endpoint respond, and how long did the request take?", "bg-sky-100 text-sky-600"],
  [LockKeyhole, "Authorization", "Did protected-resource discovery, token exchange, or scope validation fail?", "bg-violet-100 text-violet-600"],
  [Route, "Tool execution", "Which tool was called, what result came back, and did the client retry?", "bg-brand-soft text-brand-strong"],
  [CircleAlert, "Workflow outcome", "Did the multi-step task finish, or did the agent abandon the session?", "bg-amber-100 text-amber-600"],
];

function RemoteFlow() {
  return <div className="relative overflow-hidden rounded-2xl border border-line bg-white p-5 shadow-[0_30px_80px_-50px_rgba(10,10,10,0.35)] sm:p-7"><DotGrid className="scale-125 opacity-45" /><div className="relative"><div className="mb-6 flex items-center justify-between"><span className="font-mono text-[12px] uppercase tracking-[0.08em] text-faint">remote HTTP trace</span><span className="rounded-full bg-mint px-2.5 py-1 text-[11px] font-medium text-mint-ink">complete</span></div><div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:gap-0">{["client", "metadata", "authorize", "tools/call", "outcome"].map((label, i) => <div key={label} className="flex flex-1 items-center sm:flex-col sm:items-stretch"><div className="flex items-center gap-3 sm:block"><span className={`grid h-9 w-9 place-items-center rounded-full border-2 text-[11px] font-semibold ${i === 4 ? "border-brand bg-brand text-white" : "border-line-strong bg-white text-muted"}`}>{i + 1}</span><span className="text-[12px] font-medium text-body sm:mt-3 sm:block">{label}</span></div>{i < 4 && <span aria-hidden className="ml-3 h-5 w-px bg-line-strong sm:mx-auto sm:mt-3 sm:h-px sm:w-full" />}</div>)}</div><div className="mt-7 grid gap-3 sm:grid-cols-3"><div className="rounded-xl border border-line bg-paper px-4 py-3"><p className="font-mono text-[11px] text-faint">401</p><p className="mt-1 text-[13px] font-medium text-body">auth challenge visible</p></div><div className="rounded-xl border border-line bg-paper px-4 py-3"><p className="font-mono text-[11px] text-faint">tools/call</p><p className="mt-1 text-[13px] font-medium text-body">search_docs · 142ms</p></div><div className="rounded-xl border border-brand/20 bg-brand-soft/40 px-4 py-3"><p className="font-mono text-[11px] text-brand-strong">result</p><p className="mt-1 text-[13px] font-medium text-brand-strong">workflow completed</p></div></div></div></div>;
}

export default function RemoteHttpObservabilityPage() {
  return <><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd).replace(/</g, "\\u003c") }} /><Nav /><main className="flex-1"><PageFrame>
    <section className="relative overflow-hidden border-b border-line"><div aria-hidden className="pointer-events-none absolute inset-x-0 top-0 h-[450px] bg-[radial-gradient(54%_40%_at_50%_-8%,rgba(22,163,74,0.08),transparent_72%)]" /><div aria-hidden className="bg-squares dots-mask-top pointer-events-none absolute inset-x-0 top-0 h-[400px] opacity-70" /><div className="relative mx-auto max-w-3xl px-6 pb-10 pt-14 text-center sm:pb-14 sm:pt-20"><Reveal><span className="inline-flex items-center gap-2 rounded-full border border-line bg-white px-3 py-1 text-[12px] font-medium text-brand shadow-sm"><span className="h-1.5 w-1.5 rounded-full bg-brand" /> Remote MCP observability</span></Reveal><Reveal delay={0.06}><h1 className="mx-auto mt-5 max-w-[16ch] text-balance text-[38px] font-medium leading-[1.05] tracking-[-0.04em] text-ink sm:text-[56px]">Observe the remote path from auth to outcome</h1></Reveal><Reveal delay={0.12}><p className="mx-auto mt-5 max-w-[58ch] text-[16px] leading-[1.55] text-muted sm:text-[18px]">Remote MCP servers add an authorization boundary before the tool call. TrackMCP helps you see the transport, protected-resource discovery, token result, tool execution, and workflow that follows.</p></Reveal><Reveal delay={0.18}><div className="mt-8 flex flex-col items-center justify-center gap-3 sm:flex-row"><EarlyAccessButton size="lg" label="Observe a remote server" /><Button href="/mcp-server-analytics/quickstart" variant="ghost" size="lg">Start with the quickstart <ArrowRight size={16} /></Button></div></Reveal></div></section>

    <section className="relative overflow-hidden border-b border-line bg-mist"><div className="mx-auto max-w-6xl px-6 py-12 sm:py-20"><Reveal><RemoteFlow /></Reveal></div></section>

    <section className="mx-auto max-w-6xl px-6 py-20 sm:py-24"><Reveal className="mx-auto max-w-2xl text-center"><span className="text-[12px] font-medium uppercase tracking-[0.04em] text-brand">What to watch</span><h2 className="mt-3 text-[30px] font-medium leading-[1.1] tracking-[-0.02em] text-ink sm:text-[36px]">Authorization is part of the user experience.</h2><p className="mx-auto mt-4 max-w-[54ch] text-[16px] leading-[1.5] text-muted">A remote server can be reachable and still unusable. Keep the auth boundary and the agent workflow in the same operational picture.</p></Reveal><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{checks.map(([Icon, title, body, color], i) => { const IconComponent = Icon as typeof Globe; return <Reveal key={title as string} delay={i * 0.06} y={20}><article className="lift h-full rounded-2xl border border-line bg-white p-5"><div className={`grid h-10 w-10 place-items-center rounded-lg ${color}`}><IconComponent size={18} /></div><h3 className="mt-5 text-[16px] font-semibold text-ink">{title as string}</h3><p className="mt-2 text-[13.5px] leading-[1.6] text-muted">{body as string}</p></article></Reveal>; })}</div></section>

    <section className="border-y border-line bg-paper"><div className="mx-auto max-w-6xl px-6 py-20 sm:py-24"><div className="grid items-center gap-12 lg:grid-cols-2"><Reveal><span className="inline-flex items-center gap-2 text-[12px] font-medium uppercase tracking-[0.04em] text-brand-strong"><ShieldCheck size={14} /> Version-aware and privacy-aware</span><h2 className="mt-3 max-w-[17ch] text-[30px] font-medium leading-[1.1] tracking-[-0.02em] text-ink sm:text-[38px]">Keep the evidence you need, redact what you do not.</h2><p className="mt-4 max-w-[46ch] text-[16px] leading-[1.55] text-muted">Protocol and authorization behavior changes over time. Record the client, deployment, status, duration, error class, and version context that lets your team reproduce a failure without shipping secrets.</p><div className="mt-7 flex flex-wrap gap-2">{["client", "protocol", "status", "duration", "error class"].map((item) => <span key={item} className="rounded-full border border-line bg-white px-3 py-1.5 font-mono text-[11.5px] text-muted">{item}</span>)}</div></Reveal><Reveal delay={0.1} y={22}><div className="rounded-2xl border border-line bg-white p-6 shadow-[0_30px_80px_-50px_rgba(10,10,10,0.3)] sm:p-8"><div className="flex items-center justify-between border-b border-line pb-4"><span className="font-mono text-[12px] text-faint">remote-call</span><span className="text-[12px] font-medium text-brand-strong">safe to investigate</span></div><div className="mt-6 space-y-4 font-mono text-[12.5px]"><div className="flex justify-between"><span className="text-faint">endpoint</span><span className="text-body">api.example.com/mcp</span></div><div className="flex justify-between"><span className="text-faint">authorization</span><span className="text-body">bearer · valid</span></div><div className="flex justify-between"><span className="text-faint">tool</span><span className="text-body">search_docs</span></div><div className="flex justify-between"><span className="text-faint">payload</span><span className="text-brand-strong">redacted locally</span></div></div></div></Reveal></div></div></section>

    <section className="mx-auto max-w-6xl px-6 py-20 sm:py-24"><Reveal y={24}><div className="relative overflow-hidden rounded-2xl bg-ink px-8 py-16 text-center text-white sm:px-12"><div aria-hidden className="pointer-events-none absolute inset-0 bg-grid opacity-[0.10]" /><div className="relative"><p className="text-[12px] font-medium uppercase tracking-[0.1em] text-emerald-300">Remote MCP observability</p><h2 className="mt-4 text-[30px] font-medium leading-[1.1] tracking-[-0.02em] text-white sm:text-[36px]">Make the invisible boundary visible.</h2><p className="mx-auto mt-4 max-w-[48ch] text-[16px] leading-[1.5] text-white/65">Follow one remote request from challenge to completed tool call.</p><div className="mt-8 flex flex-col items-center justify-center gap-3 sm:flex-row"><EarlyAccessButton variant="white" size="lg" label="Get started" /><Link href="/mcp-observability" className="inline-flex items-center gap-2 px-5 py-3 text-[14px] font-medium text-white/75 hover:text-white">Read the observability guide <ArrowRight size={15} /></Link></div></div></div></Reveal></section>
  </PageFrame></main><Footer /></>;
}
